### ISSUE TITLE
LICENSE.md missing

### ISSUE THREAD

**Issue by J-Rojas** [oneam/h264bsd#16]
Hi, could you fill in the details for licensing?

**Comment by mikolasan** [comment]
I suppose that license here must be Apache 2.0 - same as [AOSP license](https://source.android.com/setup/start/licenses), since code-base is mainly based on it. 

The suffix **bsd** might confuse, but it's definitely not releted to licensing. May be bsd = **B**roadway.js **S**imple **D**ecoder, I don't know.

**Comment by oneam** [comment]
Added. Most files have license headers and there are multiple (compatible) licenses used in the project overall.

The original decoder source predates Android and I believe was pulled from one of the BSD variants (OpenBSD or FreeBSD). That's where the name comes from.

The Broadway.js did use it first and proved that the technique could work. I nearly cleaned it up and added some better rendering hooks.
