### ISSUE TITLE
Windows BMP?

### ISSUE THREAD

**Issue by e1ioan** [oneam/h264bsd#18]
I would like to make a request, if it's not too much to ask. I would really like to see an example on how to safe frames into bmp files. I see the h264bsdNextOutputPictureBGRA but I can't figure out how to get from that to a bmp.

**Comment by e1ioan** [comment]
Never mind. I think I figured it out. If you want to put it in a example let me know and I'll send you the code.

**Comment by e1ioan** [comment]
Well, my code works, I can save the windows bmp files for each frame, but the images are upside down
![1](https://user-images.githubusercontent.com/889110/103424323-5205fd80-4b60-11eb-89af-865dd2645726.jpg)

**Comment by oneam** [comment]
Glad to see you got it working.

Windows BMP usually uses bottom-up encoding (where lines are stored left to right, bottom to top order).
This is also called "negative step" since the distance between the first pixel in each row is negative.

If you decode assuming top to bottom encoding, it will appear upside down.
