### ISSUE TITLE
The h264bsd fully doesn't render the original colors

### ISSUE THREAD

**Issue by myjimmy** [oneam/h264bsd#20]
Hi everyone

When rendering H.264 frames with this project, it fully doesn't show the original colors.
For example, when rendering the following image with this project,
[Original Image]
![Grayscale-bar-sample](https://user-images.githubusercontent.com/52309150/152032278-dbf49c11-1705-4a6e-bd9d-1769529c44d2.png)

that image is rendered as follows.
[Rendered Image]
![h264bsd-render](https://user-images.githubusercontent.com/52309150/152032323-97e5fea4-e85d-4b5c-9135-687992a6d3cb.png)

I hope you fix this issue.
Thanks.

**Comment by oneam** [comment]
The anomaly you're seeing is due to studio color range versus full color range. The best explanation I could find is here: https://en.wikipedia.org/wiki/YUV#Numerical_approximations

They are generally a pain to deal with in encoding/decoding loops

If you're input coolers are limited to studio range [16,235], the renderer will reproduce your colors exactly.

If you want to use full range colors, you will need to adjust the YCbCr conversion matrix [here](https://github.com/oneam/h264bsd/blob/655ad776b30599f052f6c686ec30fb117cb18473/wasm/h264bsd_canvas.js#L101)

I'll see if I can add a flag for switching between full and studio range.

**Comment by oneam** [comment]
I've added an optional parameter to the H264bsdCanvas 'fullRangeColor' that will assume that the input is full range color.

That should remove the clipping you're seeing.
